

// ['MODEL_CLASS_GENFOLDER', 'MODEL_CLASS_ACTIONITEM', 'MODEL_CLASS_VARIABLE', 'MODEL_CLASS_DATAFOLDER', 'MODEL_CLASS_HOLDERITEM'];

import { publicDecrypt } from "crypto";


export enum IoClasses{

	MODEL_CLASS_GENFOLDER = "MODEL_CLASS_GENFOLDER",
	MODEL_CLASS_ACTIONITEM = "MODEL_CLASS_ACTIONITEM",
	MODEL_CLASS_VARIABLE = "MODEL_CLASS_VARIABLE",
	MODEL_CLASS_DATAFOLDER = "MODEL_CLASS_DATAFOLDER",
	MODEL_CLASS_HOLDERITEM = "MODEL_CLASS_HOLDERITEM"

}